Controllers/OrganizerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using TournamentManager.Models;
using TournamentManager.ViewModels;

namespace TournamentManager.Controllers
{
    public class OrganizerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public OrganizerController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "Admin, Organizer")]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return RedirectToAction("AccessDenied", "Home");
        }

        [Authorize(Roles = "Admin, Organizer")]
        public async Task<IActionResult> RegisteredPlayers(string Player)
        {
            var role = await _roleManager.FindByNameAsync("Player");
            
            if (role == null)
            {
                return NotFound("Role not Found");
            }

            var regPlayers = new List<UserRoleViewModel>();
            
            foreach (var user in await _userManager.Users.OrderBy(r => r.LastName).ToListAsync())
            {
                var roles = await _userManager.GetRolesAsync(user);
                var users = _userManager.Users.ToList();

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    var userViewModel = new UserRoleViewModel
                    {
                        User = user,
                        Roles = roles.ToList()
                    };
                    regPlayers.Add(userViewModel);
                }
            }
                return View(regPlayers);
        }
    }
}

Views/Organizer/Index.cshtml
@{
    ViewData["Title"] = "Organizer Index";
}
<div class="text-center">
    <h2 class="display-4 page-title-highlight">Organizer Index</h2>
    <br />
    <h4>Main page for Organizer users upon login.</h4>
    <p>(organizer view)</p>
</div>

<a class="btn btn-primary" asp-area="" asp-controller="Organizer" asp-action="RegisteredPlayers">View Registered Players</a>
<a class="btn btn-primary" asp-area="" asp-controller="Tournament" asp-action="Create">Create a Tournament</a>
<a class="btn btn-primary" asp-area="" asp-controller="Tournament" asp-action="Index">View Tournaments</a>

Views/Organizer/RegisteredPlayers.cshtml
@using TournamentManager.Data;
@using TournamentManager.ViewModels;
@model List<UserRoleViewModel>

@{
    ViewData["Title"] = "Registered Players";
}
<div class="text-center">
    <h2 class="display-4">Registered Players</h2>
    <br />
    <h4>This is the page that will display all registered players to the organizers.</h4>
    <p>(organizer view)</p>
    
</div>
<table>
    <thead>
        <tr>
            <th>Current Role</th>
            <th>Display Name</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Email</th>               
        </tr>
    </thead>
    <tbody>
        @foreach (var regPlayers in Model)
        {
            <tr>
                <td>@string.Join(", ", regPlayers.Roles)</td>
                <td>@regPlayers.User.DisplayName</td>
                <td>@regPlayers.User.LastName</td>
                <td>@regPlayers.User.FirstName</td>
                <td>@regPlayers.User.Email</td>                 
            </tr>
        }
    </tbody>
</table>